### PR TITLE
Added display of param type. Changed display of return type to match.

### PR DESCRIPTION
**Pull request by KamasamaK**

### CODE REVIEW

**Comment by KamasamaK** [comment]
As discussed in Issue #77

**Comment by jcberquist** [comment]
Thanks!

**Comment by jcberquist** [comment]
I created a new release so your changes would go out sooner - I would like to give you credit, but that will have to wait til I do a larger release and add some release notes. I hope that is okay.

**Comment by KamasamaK** [comment]
Regarding credit, I am okay with however or whenever it is done.

**Pull request merged**
