### PR TITLE
Added menu items for key bindings

### PR DESCRIPTION
**Pull request by mjhagen**
See issue #8

### CODE REVIEW

**Comment by timsayshey** [comment]
That was quick! Thanks :+1:

**Comment by mjhagen** [comment]
Was simple enough to take on, let's see if @jcberquist likes it :)

**Comment by jcberquist** [comment]
Thanks @mjhagen, I need to think about this one. 

The command for opening the default settings file is there because I wanted to take into account the possibility of this package being saved under different folder names in the packages directory. Now that it is in Package Control, it has a more defined folder name, if you will (of `CFML`), but even so, I think it is worth keeping this command there, in case someone is installing manually under a different name. That said, I think only one command class is needed, since it can be modified to accept the name of the file to open as an argument to the `run` method. Also, the open file command will replace `$platform` with the platform of the current user, so we do not need to sort that out ourselves.

Obviously, though, using that would required replacing the current `Default.sublime-keymap` file with `Default (Windows).sublime-keymap`. (And adding one for Linux as well). I think that might be the way to go? I looked at the `Default` package, and there is no `Default.sublime-keymap` file, just three platform specific ones.

For reference, here is the menu item for the `Key Bindings - User` file:
```
{
    "command": "open_file", "args":
        {
            "file": "${packages}/User/Default ($platform).sublime-keymap",
            "contents": "[\n\t$0\n]\n"
         },
         "caption": "Key Bindings – User"
}
```

**Comment by mjhagen** [comment]
I completely agree, just had some quick fun with it. While I was figuring out how you did it, I had the exact same thoughts you wrote down. I ultimately decided to just make a copy of the command to alter the least amount of code but accomplish the goal and see what your thoughts were.
I looked at how some other packages do it and there are a couple of different strategies out there. SFTP for instance uses a "platform" key in the sublime-menu file and has a hard coded package folder name.

**Comment by jcberquist** [comment]
I have looked at this some more and I have decided that I will copy the default package structure, and provide a key bindings file for each platform. I am also going to update the package open_file command to accept a file name argument, so that there does not have to be an extra command class.

Also, and I did not know this before, it looks like you can only name key binding files `Default` or `Default (platform)`. (See this [doc page](https://sublime-text-unofficial-documentation.readthedocs.org/en/latest/reference/key_bindings.html#naming-keymap-files).) That means that user key binding files are always global, and not specific to a package (and that we can't name a keymap file named `cfml_package.sublime-keymap`).

**Pull request closed without merging**
